#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.clang.M4F{1,0,1.3,1
#
app.xm4f: package/cfg/app.xm4f.mak

clean::
	-$(RM) package/cfg/app.xm4f.mak
